/**
 * Path to Connection configuration file.
 */
export type ConnectionPath = string;

/**
 * Connection settings.
 */
export type ConnectionSettings = Array<any>;

/**
 * Connection secrets.
 */
export type ConnectionSecrets = Array<any>;

/**
 * Flags describing the current activation state (NMSettingsConnectionFlags).
 *
 * Since: 1.12
 *
 * @see https://developer-old.gnome.org/NetworkManager/stable/nm-dbus-types.html#NMSettingsConnectionFlags
 */
export enum ConnectionFlags {
  /**
   * An alias for numeric zero, no flags set.
   */
  NONE = 0,

  /**
   * The connection is not saved to disk. That either means, that the connection is in-memory only and currently is not backed by a file.
   * Or, that the connection is backed by a file, but has modifications in-memory that were not persisted to disk.
   */
  UNSAVED = 0x01,

  /**
   * A connection is "nm-generated" if it was generated by NetworkManger.
   * If the connection gets modified or saved by the user, the flag gets cleared. A nm-generated is also unsaved and has no backing file as it is in-memory only.
   */
  NM_GENERATED = 0x02,

  /**
   * The connection will be deleted when it disconnects.
   * That is for in-memory connections (unsaved), which are currently active but deleted on disconnect.
   * Volatile connections are always unsaved, but they are also no backing file on disk and are entirely in-memory only.
   */
  VOLATILE = 0x04,

  /**
   * the profile was generated to represent an external configuration of a networking device. Since: 1.26.
   */
  EXTERNAL = 0x08,
}

/**
 * Connection Settings Profile properties (org.freedesktop.NetworkManager.Settings.Connection).
 *
 * @see https://developer-old.gnome.org/NetworkManager/stable/gdbus-org.freedesktop.NetworkManager.Settings.Connection.html
 */
export interface ConnectionProperties {
  /**
   * If set, indicates that the in-memory state of the connection does not match the on-disk state.
   * This flag will be set when UpdateUnsaved() is called or when any connection details change, and cleared when the connection is saved to disk via Save() or from internal operations.
   */
  Unsaved: boolean;

  /**
   * Additional flags of the connection profile.
   *
   * @see ConnectionFlags
   */
  Flags: number;

  /**
   * File that stores the connection in case the connection is file-backed.
   *
   * Since: 1.12
   */
  Filename: string;
}
